"""enhance deployment fields

Revision ID: 90fab20b872e
Revises: 92fa81439b46
Create Date: 2026-06-01 20:55:57.102773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90fab20b872e'
down_revision: Union[str, None] = '92fa81439b46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.alter_column('preview_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.drop_column('logs')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deployments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logs', sa.TEXT(), nullable=True))
        batch_op.alter_column('preview_url',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)

    # ### end Alembic commands ###
