"""add dynamic task fields

Revision ID: 92fa81439b46
Revises: 0006_create_pr_deployment_tables
Create Date: 2026-06-01 10:41:11.584845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92fa81439b46'
down_revision: Union[str, None] = '0006_create_pr_deployment_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('task_type', sa.String(length=50), nullable=True))
    op.add_column('tasks', sa.Column('depends_on', sa.Text(), nullable=True))
    op.add_column('tasks', sa.Column('metadata_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'metadata_json')
    op.drop_column('tasks', 'depends_on')
    op.drop_column('tasks', 'task_type')
    # ### end Alembic commands ###
